### ISSUE TITLE
 No module named 'jinja2'

### ISSUE THREAD

**Issue by jieruyao49** [zengxianyu/logger#1]
when I ran the code, I get this error message.How to solve it?
`Traceback (most recent call last):
  File "/home/rubyyao/PycharmProjects/jsws/weak_seg_full_sal_train.py", line 16, in <module>
    from logger import Logger
  File "/home/rubyyao/PycharmProjects/jsws/logger/__init__.py", line 1, in <module>
    from .logger import Logger
  File "/home/rubyyao/PycharmProjects/jsws/logger/logger.py", line 1, in <module>
    from jinja2 import Environment, FileSystemLoader
ModuleNotFoundError: No module named 'jinja2'`

**Comment by zengxianyu** [comment]
you will need to install the jinja2
